version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: votestream-app
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/votes
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - net

  nginx:
    image: nginx:alpine
    container_name: votestream-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - net

  db:
    image: postgres:16
    container_name: votestream-db
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: votes
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - net

  redis:
    image: redis:7
    container_name: votestream-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - net

volumes:
  dbdata:
    name: votestream-dbdata

networks:
  net:
    name: votestream-network