version: "3.9"
services:
  app:
    build: ./app
    depends_on: [db, redis]
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/votes
      REDIS_URL: redis://redis:6379/0
    networks: [net]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on: [app]
    networks: [net]

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: votes
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [net]

  redis:
    image: redis:7
    networks: [net]

volumes:
  dbdata:

networks:
  net: